In [1]:
import pandas as pd 
import numpy as np  
df3 = pd.read_csv('/home/dipankar/Desktop/crypto_price_prediction/data/raw/BTCUSDT_5m_UTC_18-08-2011_to_21-08-2026.csv')
print(df3.head())
df3.shape
df3.info()
df3.describe()

           ts_ms               datetime_utc  open  high   low  close  \
0  1313670900000  2011-08-18T12:35:00+00:00  10.9  10.9  10.9   10.9
1  1313671200000  2011-08-18T12:40:00+00:00  10.9  10.9  10.9   10.9
2  1313671500000  2011-08-18T12:45:00+00:00  10.9  10.9  10.9   10.9
3  1313671800000  2011-08-18T12:50:00+00:00  10.9  10.9  10.9   10.9
4  1313672100000  2011-08-18T12:55:00+00:00  10.9  10.9  10.9   10.9

   volume_btc  exchange  symbol quote_currency      source_dataset  \
0    0.489908  Bitstamp  BTCUSD            USD  bitstamp_2011_2021
1    0.000000  Bitstamp  BTCUSD            USD  bitstamp_2011_2021
2    0.000000  Bitstamp  BTCUSD            USD  bitstamp_2011_2021
3    0.000000  Bitstamp  BTCUSD            USD  bitstamp_2011_2021
4    0.000000  Bitstamp  BTCUSD            USD  bitstamp_2011_2021

   is_synthetic               quality_flag
0             0  observed_bitstamp_primary
1             0  observed_bitstamp_primary
2             0  observed_bitstamp_primary
3             0  observed_bitstamp_primary
4             0  observed_bitstamp_primary
<class 'pandas.DataFrame'>
RangeIndex: 1578686 entries, 0 to 1578685
Data columns (total 13 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   ts_ms           1578686 non-null  int64
 1   datetime_utc    1578686 non-null  str
 2   open            1578686 non-null  float64
 3   high            1578686 non-null  float64
 4   low             1578686 non-null  float64
 5   close           1578686 non-null  float64
 6   volume_btc      1578686 non-null  float64
 7   exchange        1578686 non-null  str
 8   symbol          1578686 non-null  str
 9   quote_currency  1578686 non-null  str
 10  source_dataset  1578686 non-null  str
 11  is_synthetic    1578686 non-null  int64
 12  quality_flag    1578686 non-null  str
dtypes: float64(5), int64(2), str(6)
memory usage: 156.6 MB

,ts_ms,open,high,low,close,volume_btc,is_synthetic
count,1.578686e+06,1.578686e+06,1.578686e+06,1.578686e+06,1.578686e+06,1.578686e+06,1.578686e+06
mean,1.550474e+12,2.326093e+04,2.328581e+04,2.323554e+04,2.326097e+04,1.371237e+02,6.017663e-05
std,1.367183e+11,3.123984e+04,3.126682e+04,3.121245e+04,3.123986e+04,3.055164e+02,7.757129e-03
min,1.313671e+12,2.220000e+00,2.230000e+00,2.220000e+00,2.230000e+00,0.000000e+00,0.000000e+00
25%,1.432072e+12,4.305800e+02,4.310600e+02,4.300000e+02,4.306000e+02,9.345817e+00,0.000000e+00
50%,1.550474e+12,7.673000e+03,7.686650e+03,7.660000e+03,7.673455e+03,5.099768e+01,0.000000e+00
75%,1.668875e+12,3.832499e+04,3.839196e+04,3.826000e+04,3.832500e+04,1.361374e+02,0.000000e+00
max,1.787276e+12,1.260112e+05,1.261996e+05,1.258681e+05,1.260112e+05,1.565993e+04,1.000000e+00

In [4]:
#Checking for the null and the duplicate values
print("Number of null values and duplicate values in the dataset:")
print(df3.isnull().sum())
print("Number of duplicate values in the dataset:")
print(df3.duplicated().sum())

Number of null values and duplicate values in the dataset:
ts_ms             0
datetime_utc      0
open              0
high              0
low               0
close             0
volume_btc        0
exchange          0
symbol            0
quote_currency    0
source_dataset    0
is_synthetic      0
quality_flag      0
dtype: int64
Number of duplicate values in the dataset:
0

In [7]:
#If there is any null and the duplicate values just drop them from the dataset
df3.dropna()
df3.drop_duplicates()

,ts_ms,datetime_utc,open,high,low,close,volume_btc,exchange,symbol,quote_currency,source_dataset,is_synthetic,quality_flag
0,1313670900000,2011-08-18T12:35:00+00:00,10.90,10.90,10.90,10.90,0.489908,Bitstamp,BTCUSD,USD,bitstamp_2011_2021,0,observed_bitstamp_primary
1,1313671200000,2011-08-18T12:40:00+00:00,10.90,10.90,10.90,10.90,0.000000,Bitstamp,BTCUSD,USD,bitstamp_2011_2021,0,observed_bitstamp_primary
2,1313671500000,2011-08-18T12:45:00+00:00,10.90,10.90,10.90,10.90,0.000000,Bitstamp,BTCUSD,USD,bitstamp_2011_2021,0,observed_bitstamp_primary
3,1313671800000,2011-08-18T12:50:00+00:00,10.90,10.90,10.90,10.90,0.000000,Bitstamp,BTCUSD,USD,bitstamp_2011_2021,0,observed_bitstamp_primary
4,1313672100000,2011-08-18T12:55:00+00:00,10.90,10.90,10.90,10.90,0.000000,Bitstamp,BTCUSD,USD,bitstamp_2011_2021,0,observed_bitstamp_primary
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1578681,1787275200000,2026-08-21T01:20:00+00:00,74659.91,74721.33,74274.52,74501.59,268.642190,Binance,BTCUSDT,USDT,binance_api_2022_now_utc,0,observed_binance_api
1578682,1787275500000,2026-08-21T01:25:00+00:00,74501.58,74800.00,74489.50,74726.77,129.114610,Binance,BTCUSDT,USDT,binance_api_2022_now_utc,0,observed_binance_api
1578683,1787275800000,2026-08-21T01:30:00+00:00,74726.78,75045.20,74600.00,74777.42,369.457220,Binance,BTCUSDT,USDT,binance_api_2022_now_utc,0,observed_binance_api
1578684,1787276100000,2026-08-21T01:35:00+00:00,74777.42,74797.30,74540.96,74610.03,191.111930,Binance,BTCUSDT,USDT,binance_api_2022_now_utc,0,observed_binance_api
1578685,1787276400000,2026-08-21T01:40:00+00:00,74610.03,74798.00,74552.00,74744.04,106.956990,Binance,BTCUSDT,USDT,binance_api_2022_now_utc,0,observed_binance_api

In [8]:
#Removing the unnecessary attributes from the dataset
df3.drop(['exchange','symbol','quote_currency','source_dataset','is_synthetic','quality_flag'], axis=1, inplace=True)

In [11]:
#checking the columns of the dataset
print("Columns of the dataset:")
print(df3.columns)

Columns of the dataset:
Index(['ts_ms', 'datetime_utc', 'open', 'high', 'low', 'close', 'volume_btc'], dtype='str')

In [ ]:
#Adding the log returns of the close price to the dataset
df3["log_return_5m"] = np.log(df3["close"] / df3["close"].shift(1))

df3["log_return_15m"] = np.log(df3["close"] / df3["close"].shift(3))

print("First 5 rows of the dataset with new features:")
print(df3.head(100))

First 5 rows of the dataset with new features:
            ts_ms               datetime_utc  open  high   low  close  \
0   1313670900000  2011-08-18T12:35:00+00:00  10.9  10.9  10.9   10.9
1   1313671200000  2011-08-18T12:40:00+00:00  10.9  10.9  10.9   10.9
2   1313671500000  2011-08-18T12:45:00+00:00  10.9  10.9  10.9   10.9
3   1313671800000  2011-08-18T12:50:00+00:00  10.9  10.9  10.9   10.9
4   1313672100000  2011-08-18T12:55:00+00:00  10.9  10.9  10.9   10.9
..            ...                        ...   ...   ...   ...    ...
95  1313699400000  2011-08-18T20:30:00+00:00  10.9  10.9  10.9   10.9
96  1313699700000  2011-08-18T20:35:00+00:00  10.9  10.9  10.9   10.9
97  1313700000000  2011-08-18T20:40:00+00:00  10.9  10.9  10.9   10.9
98  1313700300000  2011-08-18T20:45:00+00:00  10.9  10.9  10.9   10.9
99  1313700600000  2011-08-18T20:50:00+00:00  10.9  10.9  10.9   10.9

    volume_btc  log_return_5m  log_return_15m
0     0.489908            NaN             NaN
1     0.000000            0.0             NaN
2     0.000000            0.0             NaN
3     0.000000            0.0             0.0
4     0.000000            0.0             0.0
..         ...            ...             ...
95    0.000000            0.0             0.0
96    0.000000            0.0             0.0
97    0.000000            0.0             0.0
98    0.000000            0.0             0.0
99    0.000000            0.0             0.0

[100 rows x 9 columns]

In [ ]:
#Adding the Technical indicators to the dataset
#Adding the momentum, trend and volatility 
from ta.momentum import RSIIndicator
from ta.trend import MACD
from ta.volatility import BollingerBands
# RSI
rsi = RSIIndicator(df3['close'], window=14)
df3['rsi'] = rsi.rsi()

# MACD
macd = MACD(df3['close'], window_slow=26, window_fast=12, window_sign=9, fillna=False)
df3['macd'] = macd.macd()
# Bollinger Bands
bollinger = BollingerBands(df3['close'], window=20, window_dev=2)
df3['bollinger_hband'] = bollinger.bollinger_hband()
df3['bollinger_lband'] = bollinger.bollinger_lband()
df3['bollinger_mavg'] = bollinger.bollinger_mavg()
print("First 5 rows of the dataset with new features:")
print(df3.head(45))

First 5 rows of the dataset with new features:
            ts_ms               datetime_utc  open  high   low  close  \
0   1313670900000  2011-08-18T12:35:00+00:00  10.9  10.9  10.9   10.9
1   1313671200000  2011-08-18T12:40:00+00:00  10.9  10.9  10.9   10.9
2   1313671500000  2011-08-18T12:45:00+00:00  10.9  10.9  10.9   10.9
3   1313671800000  2011-08-18T12:50:00+00:00  10.9  10.9  10.9   10.9
4   1313672100000  2011-08-18T12:55:00+00:00  10.9  10.9  10.9   10.9
5   1313672400000  2011-08-18T13:00:00+00:00  10.9  10.9  10.9   10.9
6   1313672700000  2011-08-18T13:05:00+00:00  10.9  10.9  10.9   10.9
7   1313673000000  2011-08-18T13:10:00+00:00  10.9  10.9  10.9   10.9
8   1313673300000  2011-08-18T13:15:00+00:00  10.9  10.9  10.9   10.9
9   1313673600000  2011-08-18T13:20:00+00:00  10.9  10.9  10.9   10.9
10  1313673900000  2011-08-18T13:25:00+00:00  10.9  10.9  10.9   10.9
11  1313674200000  2011-08-18T13:30:00+00:00  10.9  10.9  10.9   10.9
12  1313674500000  2011-08-18T13:35:00+00:00  10.9  10.9  10.9   10.9
13  1313674800000  2011-08-18T13:40:00+00:00  10.9  10.9  10.9   10.9
14  1313675100000  2011-08-18T13:45:00+00:00  10.9  10.9  10.9   10.9
15  1313675400000  2011-08-18T13:50:00+00:00  10.9  10.9  10.9   10.9
16  1313675700000  2011-08-18T13:55:00+00:00  10.9  10.9  10.9   10.9
17  1313676000000  2011-08-18T14:00:00+00:00  10.9  10.9  10.9   10.9
18  1313676300000  2011-08-18T14:05:00+00:00  10.9  10.9  10.9   10.9
19  1313676600000  2011-08-18T14:10:00+00:00  10.9  10.9  10.9   10.9
20  1313676900000  2011-08-18T14:15:00+00:00  10.9  10.9  10.9   10.9
21  1313677200000  2011-08-18T14:20:00+00:00  10.9  10.9  10.9   10.9
22  1313677500000  2011-08-18T14:25:00+00:00  10.9  10.9  10.9   10.9
23  1313677800000  2011-08-18T14:30:00+00:00  10.9  10.9  10.9   10.9
24  1313678100000  2011-08-18T14:35:00+00:00  10.9  10.9  10.9   10.9
25  1313678400000  2011-08-18T14:40:00+00:00  10.9  10.9  10.9   10.9
26  1313678700000  2011-08-18T14:45:00+00:00  10.9  10.9  10.9   10.9
27  1313679000000  2011-08-18T14:50:00+00:00  10.9  10.9  10.9   10.9
28  1313679300000  2011-08-18T14:55:00+00:00  10.9  10.9  10.9   10.9
29  1313679600000  2011-08-18T15:00:00+00:00  10.9  10.9  10.9   10.9
30  1313679900000  2011-08-18T15:05:00+00:00  10.9  10.9  10.9   10.9
31  1313680200000  2011-08-18T15:10:00+00:00  10.9  10.9  10.9   10.9
32  1313680500000  2011-08-18T15:15:00+00:00  10.9  10.9  10.9   10.9
33  1313680800000  2011-08-18T15:20:00+00:00  10.9  10.9  10.9   10.9
34  1313681100000  2011-08-18T15:25:00+00:00  10.9  10.9  10.9   10.9
35  1313681400000  2011-08-18T15:30:00+00:00  10.9  10.9  10.9   10.9
36  1313681700000  2011-08-18T15:35:00+00:00  10.9  10.9  10.9   10.9
37  1313682000000  2011-08-18T15:40:00+00:00  10.9  10.9  10.9   10.9
38  1313682300000  2011-08-18T15:45:00+00:00  10.9  10.9  10.9   10.9
39  1313682600000  2011-08-18T15:50:00+00:00  10.9  10.9  10.9   10.9
40  1313682900000  2011-08-18T15:55:00+00:00  10.9  10.9  10.9   10.9
41  1313683200000  2011-08-18T16:00:00+00:00  10.9  10.9  10.9   10.9
42  1313683500000  2011-08-18T16:05:00+00:00  10.9  10.9  10.9   10.9
43  1313683800000  2011-08-18T16:10:00+00:00  10.9  10.9  10.9   10.9
44  1313684100000  2011-08-18T16:15:00+00:00  10.9  10.9  10.9   10.9

    volume_btc  log_return_5m  log_return_15m    rsi  macd  bollinger_hband  \
0     0.489908            NaN             NaN    NaN   NaN              NaN
1     0.000000            0.0             NaN    NaN   NaN              NaN
2     0.000000            0.0             NaN    NaN   NaN              NaN
3     0.000000            0.0             0.0    NaN   NaN              NaN
4     0.000000            0.0             0.0    NaN   NaN              NaN
5     0.000000            0.0             0.0    NaN   NaN              NaN
6     0.000000            0.0             0.0    NaN   NaN              NaN
7     0.000000            0.0             0.0    NaN   NaN              NaN
8     0.000000            0.0             0.0    NaN   NaN              NaN
9     0.000000            0.0             0.0    NaN   NaN              NaN
10    0.000000            0.0             0.0    NaN   NaN              NaN
11    0.000000            0.0             0.0    NaN   NaN              NaN
12    0.000000            0.0             0.0    NaN   NaN              NaN
13    0.000000            0.0             0.0  100.0   NaN              NaN
14    0.000000            0.0             0.0  100.0   NaN              NaN
15    0.000000            0.0             0.0  100.0   NaN              NaN
16    0.000000            0.0             0.0  100.0   NaN              NaN
17    0.000000            0.0             0.0  100.0   NaN              NaN
18    0.000000            0.0             0.0  100.0   NaN              NaN
19    0.000000            0.0             0.0  100.0   NaN             10.9
20    0.000000            0.0             0.0  100.0   NaN             10.9
21    0.000000            0.0             0.0  100.0   NaN             10.9
22    0.000000            0.0             0.0  100.0   NaN             10.9
23    0.000000            0.0             0.0  100.0   NaN             10.9
24    0.000000            0.0             0.0  100.0   NaN             10.9
25    0.000000            0.0             0.0  100.0   0.0             10.9
26    0.000000            0.0             0.0  100.0   0.0             10.9
27    0.000000            0.0             0.0  100.0   0.0             10.9
28    0.000000            0.0             0.0  100.0   0.0             10.9
29    0.000000            0.0             0.0  100.0   0.0             10.9
30    0.000000            0.0             0.0  100.0   0.0             10.9
31    0.000000            0.0             0.0  100.0   0.0             10.9
32    0.000000            0.0             0.0  100.0   0.0             10.9
33    0.000000            0.0             0.0  100.0   0.0             10.9
34    0.000000            0.0             0.0  100.0   0.0             10.9
35    0.000000            0.0             0.0  100.0   0.0             10.9
36    0.000000            0.0             0.0  100.0   0.0             10.9
37    0.000000            0.0             0.0  100.0   0.0             10.9
38    0.000000            0.0             0.0  100.0   0.0             10.9
39    0.000000            0.0             0.0  100.0   0.0             10.9
40    0.000000            0.0             0.0  100.0   0.0             10.9
41    0.000000            0.0             0.0  100.0   0.0             10.9
42    0.000000            0.0             0.0  100.0   0.0             10.9
43    0.000000            0.0             0.0  100.0   0.0             10.9
44    0.000000            0.0             0.0  100.0   0.0             10.9

    bollinger_lband  bollinger_mavg
0               NaN             NaN
1               NaN             NaN
2               NaN             NaN
3               NaN             NaN
4               NaN             NaN
5               NaN             NaN
6               NaN             NaN
7               NaN             NaN
8               NaN             NaN
9               NaN             NaN
10              NaN             NaN
11              NaN             NaN
12              NaN             NaN
13              NaN             NaN
14              NaN             NaN
15              NaN             NaN
16              NaN             NaN
17              NaN             NaN
18              NaN             NaN
19             10.9            10.9
20             10.9            10.9
21             10.9            10.9
22             10.9            10.9
23             10.9            10.9
24             10.9            10.9
25             10.9            10.9
26             10.9            10.9
27             10.9            10.9
28             10.9            10.9
29             10.9            10.9
30             10.9            10.9
31             10.9            10.9
32             10.9            10.9
33             10.9            10.9
34             10.9            10.9
35             10.9            10.9
36             10.9            10.9
37             10.9            10.9
38             10.9            10.9
39             10.9            10.9
40             10.9            10.9
41             10.9            10.9
42             10.9            10.9
43             10.9            10.9
44             10.9            10.9

In [17]:
#Adding the target variable to the dataset
df3["target_log_return_5m"] = np.log(
    df3["close"].shift(-1) / df3["close"]
)
df3["target_log_return_15m"] = np.log(
    df3["close"].shift(-3) / df3["close"]
)
print("First 45 rows of the dataset with new features:")
print(df3.head(45))

First 45 rows of the dataset with new features:
            ts_ms               datetime_utc  open  high   low  close  \
0   1313670900000  2011-08-18T12:35:00+00:00  10.9  10.9  10.9   10.9
1   1313671200000  2011-08-18T12:40:00+00:00  10.9  10.9  10.9   10.9
2   1313671500000  2011-08-18T12:45:00+00:00  10.9  10.9  10.9   10.9
3   1313671800000  2011-08-18T12:50:00+00:00  10.9  10.9  10.9   10.9
4   1313672100000  2011-08-18T12:55:00+00:00  10.9  10.9  10.9   10.9
5   1313672400000  2011-08-18T13:00:00+00:00  10.9  10.9  10.9   10.9
6   1313672700000  2011-08-18T13:05:00+00:00  10.9  10.9  10.9   10.9
7   1313673000000  2011-08-18T13:10:00+00:00  10.9  10.9  10.9   10.9
8   1313673300000  2011-08-18T13:15:00+00:00  10.9  10.9  10.9   10.9
9   1313673600000  2011-08-18T13:20:00+00:00  10.9  10.9  10.9   10.9
10  1313673900000  2011-08-18T13:25:00+00:00  10.9  10.9  10.9   10.9
11  1313674200000  2011-08-18T13:30:00+00:00  10.9  10.9  10.9   10.9
12  1313674500000  2011-08-18T13:35:00+00:00  10.9  10.9  10.9   10.9
13  1313674800000  2011-08-18T13:40:00+00:00  10.9  10.9  10.9   10.9
14  1313675100000  2011-08-18T13:45:00+00:00  10.9  10.9  10.9   10.9
15  1313675400000  2011-08-18T13:50:00+00:00  10.9  10.9  10.9   10.9
16  1313675700000  2011-08-18T13:55:00+00:00  10.9  10.9  10.9   10.9
17  1313676000000  2011-08-18T14:00:00+00:00  10.9  10.9  10.9   10.9
18  1313676300000  2011-08-18T14:05:00+00:00  10.9  10.9  10.9   10.9
19  1313676600000  2011-08-18T14:10:00+00:00  10.9  10.9  10.9   10.9
20  1313676900000  2011-08-18T14:15:00+00:00  10.9  10.9  10.9   10.9
21  1313677200000  2011-08-18T14:20:00+00:00  10.9  10.9  10.9   10.9
22  1313677500000  2011-08-18T14:25:00+00:00  10.9  10.9  10.9   10.9
23  1313677800000  2011-08-18T14:30:00+00:00  10.9  10.9  10.9   10.9
24  1313678100000  2011-08-18T14:35:00+00:00  10.9  10.9  10.9   10.9
25  1313678400000  2011-08-18T14:40:00+00:00  10.9  10.9  10.9   10.9
26  1313678700000  2011-08-18T14:45:00+00:00  10.9  10.9  10.9   10.9
27  1313679000000  2011-08-18T14:50:00+00:00  10.9  10.9  10.9   10.9
28  1313679300000  2011-08-18T14:55:00+00:00  10.9  10.9  10.9   10.9
29  1313679600000  2011-08-18T15:00:00+00:00  10.9  10.9  10.9   10.9
30  1313679900000  2011-08-18T15:05:00+00:00  10.9  10.9  10.9   10.9
31  1313680200000  2011-08-18T15:10:00+00:00  10.9  10.9  10.9   10.9
32  1313680500000  2011-08-18T15:15:00+00:00  10.9  10.9  10.9   10.9
33  1313680800000  2011-08-18T15:20:00+00:00  10.9  10.9  10.9   10.9
34  1313681100000  2011-08-18T15:25:00+00:00  10.9  10.9  10.9   10.9
35  1313681400000  2011-08-18T15:30:00+00:00  10.9  10.9  10.9   10.9
36  1313681700000  2011-08-18T15:35:00+00:00  10.9  10.9  10.9   10.9
37  1313682000000  2011-08-18T15:40:00+00:00  10.9  10.9  10.9   10.9
38  1313682300000  2011-08-18T15:45:00+00:00  10.9  10.9  10.9   10.9
39  1313682600000  2011-08-18T15:50:00+00:00  10.9  10.9  10.9   10.9
40  1313682900000  2011-08-18T15:55:00+00:00  10.9  10.9  10.9   10.9
41  1313683200000  2011-08-18T16:00:00+00:00  10.9  10.9  10.9   10.9
42  1313683500000  2011-08-18T16:05:00+00:00  10.9  10.9  10.9   10.9
43  1313683800000  2011-08-18T16:10:00+00:00  10.9  10.9  10.9   10.9
44  1313684100000  2011-08-18T16:15:00+00:00  10.9  10.9  10.9   10.9

    volume_btc  log_return_5m  log_return_15m    rsi  macd  bollinger_hband  \
0     0.489908            NaN             NaN    NaN   NaN              NaN
1     0.000000            0.0             NaN    NaN   NaN              NaN
2     0.000000            0.0             NaN    NaN   NaN              NaN
3     0.000000            0.0             0.0    NaN   NaN              NaN
4     0.000000            0.0             0.0    NaN   NaN              NaN
5     0.000000            0.0             0.0    NaN   NaN              NaN
6     0.000000            0.0             0.0    NaN   NaN              NaN
7     0.000000            0.0             0.0    NaN   NaN              NaN
8     0.000000            0.0             0.0    NaN   NaN              NaN
9     0.000000            0.0             0.0    NaN   NaN              NaN
10    0.000000            0.0             0.0    NaN   NaN              NaN
11    0.000000            0.0             0.0    NaN   NaN              NaN
12    0.000000            0.0             0.0    NaN   NaN              NaN
13    0.000000            0.0             0.0  100.0   NaN              NaN
14    0.000000            0.0             0.0  100.0   NaN              NaN
15    0.000000            0.0             0.0  100.0   NaN              NaN
16    0.000000            0.0             0.0  100.0   NaN              NaN
17    0.000000            0.0             0.0  100.0   NaN              NaN
18    0.000000            0.0             0.0  100.0   NaN              NaN
19    0.000000            0.0             0.0  100.0   NaN             10.9
20    0.000000            0.0             0.0  100.0   NaN             10.9
21    0.000000            0.0             0.0  100.0   NaN             10.9
22    0.000000            0.0             0.0  100.0   NaN             10.9
23    0.000000            0.0             0.0  100.0   NaN             10.9
24    0.000000            0.0             0.0  100.0   NaN             10.9
25    0.000000            0.0             0.0  100.0   0.0             10.9
26    0.000000            0.0             0.0  100.0   0.0             10.9
27    0.000000            0.0             0.0  100.0   0.0             10.9
28    0.000000            0.0             0.0  100.0   0.0             10.9
29    0.000000            0.0             0.0  100.0   0.0             10.9
30    0.000000            0.0             0.0  100.0   0.0             10.9
31    0.000000            0.0             0.0  100.0   0.0             10.9
32    0.000000            0.0             0.0  100.0   0.0             10.9
33    0.000000            0.0             0.0  100.0   0.0             10.9
34    0.000000            0.0             0.0  100.0   0.0             10.9
35    0.000000            0.0             0.0  100.0   0.0             10.9
36    0.000000            0.0             0.0  100.0   0.0             10.9
37    0.000000            0.0             0.0  100.0   0.0             10.9
38    0.000000            0.0             0.0  100.0   0.0             10.9
39    0.000000            0.0             0.0  100.0   0.0             10.9
40    0.000000            0.0             0.0  100.0   0.0             10.9
41    0.000000            0.0             0.0  100.0   0.0             10.9
42    0.000000            0.0             0.0  100.0   0.0             10.9
43    0.000000            0.0             0.0  100.0   0.0             10.9
44    0.000000            0.0             0.0  100.0   0.0             10.9

    bollinger_lband  bollinger_mavg  target_log_return_5m  \
0               NaN             NaN                   0.0
1               NaN             NaN                   0.0
2               NaN             NaN                   0.0
3               NaN             NaN                   0.0
4               NaN             NaN                   0.0
5               NaN             NaN                   0.0
6               NaN             NaN                   0.0
7               NaN             NaN                   0.0
8               NaN             NaN                   0.0
9               NaN             NaN                   0.0
10              NaN             NaN                   0.0
11              NaN             NaN                   0.0
12              NaN             NaN                   0.0
13              NaN             NaN                   0.0
14              NaN             NaN                   0.0
15              NaN             NaN                   0.0
16              NaN             NaN                   0.0
17              NaN             NaN                   0.0
18              NaN             NaN                   0.0
19             10.9            10.9                   0.0
20             10.9            10.9                   0.0
21             10.9            10.9                   0.0
22             10.9            10.9                   0.0
23             10.9            10.9                   0.0
24             10.9            10.9                   0.0
25             10.9            10.9                   0.0
26             10.9            10.9                   0.0
27             10.9            10.9                   0.0
28             10.9            10.9                   0.0
29             10.9            10.9                   0.0
30             10.9            10.9                   0.0
31             10.9            10.9                   0.0
32             10.9            10.9                   0.0
33             10.9            10.9                   0.0
34             10.9            10.9                   0.0
35             10.9            10.9                   0.0
36             10.9            10.9                   0.0
37             10.9            10.9                   0.0
38             10.9            10.9                   0.0
39             10.9            10.9                   0.0
40             10.9            10.9                   0.0
41             10.9            10.9                   0.0
42             10.9            10.9                   0.0
43             10.9            10.9                   0.0
44             10.9            10.9                   0.0

    target_log_return_15m
0                     0.0
1                     0.0
2                     0.0
3                     0.0
4                     0.0
5                     0.0
6                     0.0
7                     0.0
8                     0.0
9                     0.0
10                    0.0
11                    0.0
12                    0.0
13                    0.0
14                    0.0
15                    0.0
16                    0.0
17                    0.0
18                    0.0
19                    0.0
20                    0.0
21                    0.0
22                    0.0
23                    0.0
24                    0.0
25                    0.0
26                    0.0
27                    0.0
28                    0.0
29                    0.0
30                    0.0
31                    0.0
32                    0.0
33                    0.0
34                    0.0
35                    0.0
36                    0.0
37                    0.0
38                    0.0
39                    0.0
40                    0.0
41                    0.0
42                    0.0
43                    0.0
44                    0.0

In [18]:
#Phase 7: Dropping the missing values from the dataset
df3 = df3.dropna().reset_index(drop=True)
df3 = df3.drop_duplicates().reset_index(drop=True)
print("Dataset after dropping missing values:")
print(df3.isna().sum())
print("Number of duplicate values in the dataset:")
print(df3.duplicated().sum())
print(df3.head(45))

Dataset after dropping missing values:
ts_ms                    0
datetime_utc             0
open                     0
high                     0
low                      0
close                    0
volume_btc               0
log_return_5m            0
log_return_15m           0
rsi                      0
macd                     0
bollinger_hband          0
bollinger_lband          0
bollinger_mavg           0
target_log_return_5m     0
target_log_return_15m    0
dtype: int64
Number of duplicate values in the dataset:
0
            ts_ms               datetime_utc  open  high   low  close  \
0   1313678400000  2011-08-18T14:40:00+00:00  10.9  10.9  10.9   10.9
1   1313678700000  2011-08-18T14:45:00+00:00  10.9  10.9  10.9   10.9
2   1313679000000  2011-08-18T14:50:00+00:00  10.9  10.9  10.9   10.9
3   1313679300000  2011-08-18T14:55:00+00:00  10.9  10.9  10.9   10.9
4   1313679600000  2011-08-18T15:00:00+00:00  10.9  10.9  10.9   10.9
5   1313679900000  2011-08-18T15:05:00+00:00  10.9  10.9  10.9   10.9
6   1313680200000  2011-08-18T15:10:00+00:00  10.9  10.9  10.9   10.9
7   1313680500000  2011-08-18T15:15:00+00:00  10.9  10.9  10.9   10.9
8   1313680800000  2011-08-18T15:20:00+00:00  10.9  10.9  10.9   10.9
9   1313681100000  2011-08-18T15:25:00+00:00  10.9  10.9  10.9   10.9
10  1313681400000  2011-08-18T15:30:00+00:00  10.9  10.9  10.9   10.9
11  1313681700000  2011-08-18T15:35:00+00:00  10.9  10.9  10.9   10.9
12  1313682000000  2011-08-18T15:40:00+00:00  10.9  10.9  10.9   10.9
13  1313682300000  2011-08-18T15:45:00+00:00  10.9  10.9  10.9   10.9
14  1313682600000  2011-08-18T15:50:00+00:00  10.9  10.9  10.9   10.9
15  1313682900000  2011-08-18T15:55:00+00:00  10.9  10.9  10.9   10.9
16  1313683200000  2011-08-18T16:00:00+00:00  10.9  10.9  10.9   10.9
17  1313683500000  2011-08-18T16:05:00+00:00  10.9  10.9  10.9   10.9
18  1313683800000  2011-08-18T16:10:00+00:00  10.9  10.9  10.9   10.9
19  1313684100000  2011-08-18T16:15:00+00:00  10.9  10.9  10.9   10.9
20  1313684400000  2011-08-18T16:20:00+00:00  10.9  10.9  10.9   10.9
21  1313684700000  2011-08-18T16:25:00+00:00  10.9  10.9  10.9   10.9
22  1313685000000  2011-08-18T16:30:00+00:00  10.9  10.9  10.9   10.9
23  1313685300000  2011-08-18T16:35:00+00:00  10.9  10.9  10.9   10.9
24  1313685600000  2011-08-18T16:40:00+00:00  10.9  10.9  10.9   10.9
25  1313685900000  2011-08-18T16:45:00+00:00  10.9  10.9  10.9   10.9
26  1313686200000  2011-08-18T16:50:00+00:00  10.9  10.9  10.9   10.9
27  1313686500000  2011-08-18T16:55:00+00:00  10.9  10.9  10.9   10.9
28  1313686800000  2011-08-18T17:00:00+00:00  10.9  10.9  10.9   10.9
29  1313687100000  2011-08-18T17:05:00+00:00  10.9  10.9  10.9   10.9
30  1313687400000  2011-08-18T17:10:00+00:00  10.9  10.9  10.9   10.9
31  1313687700000  2011-08-18T17:15:00+00:00  10.9  10.9  10.9   10.9
32  1313688000000  2011-08-18T17:20:00+00:00  10.9  10.9  10.9   10.9
33  1313688300000  2011-08-18T17:25:00+00:00  10.9  10.9  10.9   10.9
34  1313688600000  2011-08-18T17:30:00+00:00  10.9  10.9  10.9   10.9
35  1313688900000  2011-08-18T17:35:00+00:00  10.9  10.9  10.9   10.9
36  1313689200000  2011-08-18T17:40:00+00:00  10.9  10.9  10.9   10.9
37  1313689500000  2011-08-18T17:45:00+00:00  10.9  10.9  10.9   10.9
38  1313689800000  2011-08-18T17:50:00+00:00  10.9  10.9  10.9   10.9
39  1313690100000  2011-08-18T17:55:00+00:00  10.9  10.9  10.9   10.9
40  1313690400000  2011-08-18T18:00:00+00:00  10.9  10.9  10.9   10.9
41  1313690700000  2011-08-18T18:05:00+00:00  10.9  10.9  10.9   10.9
42  1313691000000  2011-08-18T18:10:00+00:00  10.9  10.9  10.9   10.9
43  1313691300000  2011-08-18T18:15:00+00:00  10.9  10.9  10.9   10.9
44  1313691600000  2011-08-18T18:20:00+00:00  10.9  10.9  10.9   10.9

    volume_btc  log_return_5m  log_return_15m    rsi  macd  bollinger_hband  \
0          0.0            0.0             0.0  100.0   0.0             10.9
1          0.0            0.0             0.0  100.0   0.0             10.9
2          0.0            0.0             0.0  100.0   0.0             10.9
3          0.0            0.0             0.0  100.0   0.0             10.9
4          0.0            0.0             0.0  100.0   0.0             10.9
5          0.0            0.0             0.0  100.0   0.0             10.9
6          0.0            0.0             0.0  100.0   0.0             10.9
7          0.0            0.0             0.0  100.0   0.0             10.9
8          0.0            0.0             0.0  100.0   0.0             10.9
9          0.0            0.0             0.0  100.0   0.0             10.9
10         0.0            0.0             0.0  100.0   0.0             10.9
11         0.0            0.0             0.0  100.0   0.0             10.9
12         0.0            0.0             0.0  100.0   0.0             10.9
13         0.0            0.0             0.0  100.0   0.0             10.9
14         0.0            0.0             0.0  100.0   0.0             10.9
15         0.0            0.0             0.0  100.0   0.0             10.9
16         0.0            0.0             0.0  100.0   0.0             10.9
17         0.0            0.0             0.0  100.0   0.0             10.9
18         0.0            0.0             0.0  100.0   0.0             10.9
19         0.0            0.0             0.0  100.0   0.0             10.9
20         0.0            0.0             0.0  100.0   0.0             10.9
21         0.0            0.0             0.0  100.0   0.0             10.9
22         0.0            0.0             0.0  100.0   0.0             10.9
23         0.0            0.0             0.0  100.0   0.0             10.9
24         0.0            0.0             0.0  100.0   0.0             10.9
25         0.0            0.0             0.0  100.0   0.0             10.9
26         0.0            0.0             0.0  100.0   0.0             10.9
27         0.0            0.0             0.0  100.0   0.0             10.9
28         0.0            0.0             0.0  100.0   0.0             10.9
29         0.0            0.0             0.0  100.0   0.0             10.9
30         0.0            0.0             0.0  100.0   0.0             10.9
31         0.0            0.0             0.0  100.0   0.0             10.9
32         0.0            0.0             0.0  100.0   0.0             10.9
33         0.0            0.0             0.0  100.0   0.0             10.9
34         0.0            0.0             0.0  100.0   0.0             10.9
35         0.0            0.0             0.0  100.0   0.0             10.9
36         0.0            0.0             0.0  100.0   0.0             10.9
37         0.0            0.0             0.0  100.0   0.0             10.9
38         0.0            0.0             0.0  100.0   0.0             10.9
39         0.0            0.0             0.0  100.0   0.0             10.9
40         0.0            0.0             0.0  100.0   0.0             10.9
41         0.0            0.0             0.0  100.0   0.0             10.9
42         0.0            0.0             0.0  100.0   0.0             10.9
43         0.0            0.0             0.0  100.0   0.0             10.9
44         0.0            0.0             0.0  100.0   0.0             10.9

    bollinger_lband  bollinger_mavg  target_log_return_5m  \
0              10.9            10.9                   0.0
1              10.9            10.9                   0.0
2              10.9            10.9                   0.0
3              10.9            10.9                   0.0
4              10.9            10.9                   0.0
5              10.9            10.9                   0.0
6              10.9            10.9                   0.0
7              10.9            10.9                   0.0
8              10.9            10.9                   0.0
9              10.9            10.9                   0.0
10             10.9            10.9                   0.0
11             10.9            10.9                   0.0
12             10.9            10.9                   0.0
13             10.9            10.9                   0.0
14             10.9            10.9                   0.0
15             10.9            10.9                   0.0
16             10.9            10.9                   0.0
17             10.9            10.9                   0.0
18             10.9            10.9                   0.0
19             10.9            10.9                   0.0
20             10.9            10.9                   0.0
21             10.9            10.9                   0.0
22             10.9            10.9                   0.0
23             10.9            10.9                   0.0
24             10.9            10.9                   0.0
25             10.9            10.9                   0.0
26             10.9            10.9                   0.0
27             10.9            10.9                   0.0
28             10.9            10.9                   0.0
29             10.9            10.9                   0.0
30             10.9            10.9                   0.0
31             10.9            10.9                   0.0
32             10.9            10.9                   0.0
33             10.9            10.9                   0.0
34             10.9            10.9                   0.0
35             10.9            10.9                   0.0
36             10.9            10.9                   0.0
37             10.9            10.9                   0.0
38             10.9            10.9                   0.0
39             10.9            10.9                   0.0
40             10.9            10.9                   0.0
41             10.9            10.9                   0.0
42             10.9            10.9                   0.0
43             10.9            10.9                   0.0
44             10.9            10.9                   0.0

    target_log_return_15m
0                     0.0
1                     0.0
2                     0.0
3                     0.0
4                     0.0
5                     0.0
6                     0.0
7                     0.0
8                     0.0
9                     0.0
10                    0.0
11                    0.0
12                    0.0
13                    0.0
14                    0.0
15                    0.0
16                    0.0
17                    0.0
18                    0.0
19                    0.0
20                    0.0
21                    0.0
22                    0.0
23                    0.0
24                    0.0
25                    0.0
26                    0.0
27                    0.0
28                    0.0
29                    0.0
30                    0.0
31                    0.0
32                    0.0
33                    0.0
34                    0.0
35                    0.0
36                    0.0
37                    0.0
38                    0.0
39                    0.0
40                    0.0
41                    0.0
42                    0.0
43                    0.0
44                    0.0

In [19]:
print((df3 == 0).sum())

ts_ms                         0
datetime_utc                  0
open                          0
high                          0
low                           0
close                         0
volume_btc               152961
log_return_5m            207244
log_return_15m           147811
rsi                        4874
macd                        262
bollinger_hband               0
bollinger_lband               0
bollinger_mavg                0
target_log_return_5m     207243
target_log_return_15m    147808
dtype: int64

In [20]:
#saving the cleaned dataset to a new CSV file
df3.to_csv('/home/dipankar/Desktop/crypto_price_prediction/data/processed/BTCUSDT_5m_UTC_18-08-2011_to_21-08-2026_cleaned_data.csv', index=False)