In [1]:
import pandas as pd 
import numpy as np  
df4 = pd.read_csv('/home/dipankar/Desktop/crypto_price_prediction/data/raw/BTCUSD-5m-2026-10-07.csv')
print(df4.head())
df4.shape
df4.info()
df4.describe()

   1791331200000000  85558.16000000  85558.16000000.1  85558.16000000.2  \
0  1791331500000000        85475.12          85475.12          85475.00
1  1791331800000000        85557.34          85558.17          85557.34
2  1791332100000000        85558.16          85558.16          85558.16
3  1791332400000000        85475.11          85475.11          85475.11
4  1791332700000000        85475.11          85475.11          85475.11

   85558.16000000.3  0.00000000  1791331499999999  0.00000000.1  0  \
0          85475.00     0.09046  1791331799999999   7732.077887  5
1          85558.17     0.07562  1791332099999999   6469.905197  3
2          85558.16     0.07507  1791332399999999   6422.851071  1
3          85475.11     0.15344  1791332699999999  13115.300878  4
4          85475.11     0.00000  1791332999999999      0.000000  0

   0.00000000.2  0.00000000.3  0.1
0       0.00000      0.000000    0
1       0.07562   6469.905197    0
2       0.00000      0.000000    0
3       0.00000      0.000000    0
4       0.00000      0.000000    0
<class 'pandas.DataFrame'>
RangeIndex: 287 entries, 0 to 286
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   1791331200000000  287 non-null    int64
 1   85558.16000000    287 non-null    float64
 2   85558.16000000.1  287 non-null    float64
 3   85558.16000000.2  287 non-null    float64
 4   85558.16000000.3  287 non-null    float64
 5   0.00000000        287 non-null    float64
 6   1791331499999999  287 non-null    int64
 7   0.00000000.1      287 non-null    float64
 8   0                 287 non-null    int64
 9   0.00000000.2      287 non-null    float64
 10  0.00000000.3      287 non-null    float64
 11  0.1               287 non-null    int64
dtypes: float64(8), int64(4)
memory usage: 27.0 KB

,1791331200000000,85558.16000000,85558.16000000.1,85558.16000000.2,85558.16000000.3,0.00000000,1791331499999999,0.00000000.1,0,0.00000000.2,0.00000000.3,0.1
count,2.870000e+02,287.000000,287.000000,287.000000,287.000000,287.000000,2.870000e+02,287.000000,287.000000,287.000000,287.000000,287.0
mean,1.791374e+15,83764.794669,83775.451951,83740.532962,83752.785226,0.106167,1.791375e+15,8888.149514,8.679443,0.039122,3273.600691,0.0
std,2.489819e+10,606.273089,606.535781,604.302873,602.345145,0.218352,2.489819e+10,18255.803470,21.003705,0.155376,12976.429709,0.0
min,1.791332e+15,82823.520000,82823.520000,82772.540000,82823.520000,0.000000,1.791332e+15,0.000000,0.000000,0.000000,0.000000,0.0
25%,1.791353e+15,83336.250000,83336.250000,83336.250000,83336.250000,0.000000,1.791353e+15,0.000000,0.000000,0.000000,0.000000,0.0
50%,1.791374e+15,83580.580000,83629.750000,83565.040000,83586.600000,0.016190,1.791375e+15,1355.604133,2.000000,0.000000,0.000000,0.0
75%,1.791396e+15,84063.320000,84063.330000,84063.320000,84063.325000,0.111545,1.791396e+15,9322.083574,7.000000,0.001195,99.653932,0.0
max,1.791417e+15,85558.160000,85558.170000,85558.160000,85558.170000,1.529140,1.791418e+15,128454.840606,213.000000,1.378840,115151.810712,0.0

In [5]:
# Assign Binance Kline column names
df4.columns = [
    "open_time",
    "open",
    "high",
    "low",
    "close",
    "volume",
    "close_time",
    "quote_asset_volume",
    "number_of_trades",
    "taker_buy_base_asset_volume",
    "taker_buy_quote_asset_volume",
    "ignore"
]

In [6]:
print(df4.columns)
df4.head()

Index(['open_time', 'open', 'high', 'low', 'close', 'volume', 'close_time',
       'quote_asset_volume', 'number_of_trades', 'taker_buy_base_asset_volume',
       'taker_buy_quote_asset_volume', 'ignore'],
      dtype='str')

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,ignore
0,1791331500000000,85475.12,85475.12,85475.00,85475.00,0.09046,1791331799999999,7732.077887,5,0.00000,0.000000,0
1,1791331800000000,85557.34,85558.17,85557.34,85558.17,0.07562,1791332099999999,6469.905197,3,0.07562,6469.905197,0
2,1791332100000000,85558.16,85558.16,85558.16,85558.16,0.07507,1791332399999999,6422.851071,1,0.00000,0.000000,0
3,1791332400000000,85475.11,85475.11,85475.11,85475.11,0.15344,1791332699999999,13115.300878,4,0.00000,0.000000,0
4,1791332700000000,85475.11,85475.11,85475.11,85475.11,0.00000,1791332999999999,0.000000,0,0.00000,0.000000,0

In [7]:
# Convert open_time from microseconds to UTC datetime
df4["Datetime"] = pd.to_datetime(
    df4["open_time"], unit="us", utc=True
)

In [8]:
#Keeping only the required columns
df4 = df4[["Datetime", "open", "high", "low", "close", "volume"]]

In [10]:
#checking for missing and duplicate values in the dataset
print("Missing values in the dataset:")
print(df4.isna().sum())
print("Duplicate values in the dataset:")
print(df4.duplicated().sum())

Missing values in the dataset:
Datetime    0
open        0
high        0
low         0
close       0
volume      0
dtype: int64
Duplicate values in the dataset:
0

In [12]:
#removing the missing and duplicate values from the dataset
df4.dropna()
df4.drop_duplicates()

                     Datetime      open      high       low     close   volume
0   2026-10-07 00:05:00+00:00  85475.12  85475.12  85475.00  85475.00  0.09046
1   2026-10-07 00:10:00+00:00  85557.34  85558.17  85557.34  85558.17  0.07562
2   2026-10-07 00:15:00+00:00  85558.16  85558.16  85558.16  85558.16  0.07507
3   2026-10-07 00:20:00+00:00  85475.11  85475.11  85475.11  85475.11  0.15344
4   2026-10-07 00:25:00+00:00  85475.11  85475.11  85475.11  85475.11  0.00000
..                        ...       ...       ...       ...       ...      ...
282 2026-10-07 23:35:00+00:00  83397.99  83397.99  83397.99  83397.99  0.00069
283 2026-10-07 23:40:00+00:00  83336.25  83336.25  83336.25  83336.25  0.09464
284 2026-10-07 23:45:00+00:00  83336.25  83336.25  83336.25  83336.25  0.00000
285 2026-10-07 23:50:00+00:00  83247.50  83247.50  83247.50  83247.50  0.09730
286 2026-10-07 23:55:00+00:00  83247.50  83247.50  83247.50  83247.50  0.00000

[287 rows x 6 columns]

In [13]:
#Adding the log returns of the close price to the dataset
df4["log_return_5m"] = np.log(df4["close"] / df4["close"].shift(1))

df4["log_return_15m"] = np.log(df4["close"] / df4["close"].shift(3))

print("First 5 rows of the dataset with new features:")
print(df4.head(100))

First 5 rows of the dataset with new features:
                    Datetime      open      high       low     close   volume  \
0  2026-10-07 00:05:00+00:00  85475.12  85475.12  85475.00  85475.00  0.09046
1  2026-10-07 00:10:00+00:00  85557.34  85558.17  85557.34  85558.17  0.07562
2  2026-10-07 00:15:00+00:00  85558.16  85558.16  85558.16  85558.16  0.07507
3  2026-10-07 00:20:00+00:00  85475.11  85475.11  85475.11  85475.11  0.15344
4  2026-10-07 00:25:00+00:00  85475.11  85475.11  85475.11  85475.11  0.00000
..                       ...       ...       ...       ...       ...      ...
95 2026-10-07 08:00:00+00:00  84063.32  84099.91  83961.29  84063.32  0.12440
96 2026-10-07 08:05:00+00:00  84063.32  84063.32  84063.32  84063.32  0.03349
97 2026-10-07 08:10:00+00:00  84063.32  84063.32  84063.32  84063.32  0.00000
98 2026-10-07 08:15:00+00:00  83980.27  83980.27  83970.63  83970.63  0.06582
99 2026-10-07 08:20:00+00:00  83980.27  83980.27  83980.27  83980.27  0.09205

    log_return_5m  log_return_15m
0             NaN             NaN
1    9.725600e-04             NaN
2   -1.168796e-07             NaN
3   -9.711562e-04        0.000001
4    0.000000e+00       -0.000971
..            ...             ...
95  -7.602091e-04       -0.001974
96   0.000000e+00       -0.000987
97   0.000000e+00       -0.000760
98  -1.103230e-03       -0.001103
99   1.147955e-04       -0.000988

[100 rows x 8 columns]

In [14]:
#Adding the Technical indicators to the dataset
#Adding the momentum, trend and volatility 
from ta.momentum import RSIIndicator
from ta.trend import MACD
from ta.volatility import BollingerBands
# RSI
rsi = RSIIndicator(df4['close'], window=14)
df4['rsi'] = rsi.rsi()

# MACD
macd = MACD(df4['close'], window_slow=26, window_fast=12, window_sign=9, fillna=False)
df4['macd'] = macd.macd()
# Bollinger Bands
bollinger = BollingerBands(df4['close'], window=20, window_dev=2)
df4['bollinger_hband'] = bollinger.bollinger_hband()
df4['bollinger_lband'] = bollinger.bollinger_lband()
df4['bollinger_mavg'] = bollinger.bollinger_mavg()
print("First 5 rows of the dataset with new features:")
print(df4.head(45))

First 5 rows of the dataset with new features:
                    Datetime      open      high       low     close   volume  \
0  2026-10-07 00:05:00+00:00  85475.12  85475.12  85475.00  85475.00  0.09046
1  2026-10-07 00:10:00+00:00  85557.34  85558.17  85557.34  85558.17  0.07562
2  2026-10-07 00:15:00+00:00  85558.16  85558.16  85558.16  85558.16  0.07507
3  2026-10-07 00:20:00+00:00  85475.11  85475.11  85475.11  85475.11  0.15344
4  2026-10-07 00:25:00+00:00  85475.11  85475.11  85475.11  85475.11  0.00000
5  2026-10-07 00:30:00+00:00  85400.00  85400.00  85400.00  85400.00  0.00450
6  2026-10-07 00:35:00+00:00  85400.00  85400.00  85400.00  85400.00  0.00000
7  2026-10-07 00:40:00+00:00  85475.11  85475.11  85475.11  85475.11  0.14730
8  2026-10-07 00:45:00+00:00  85475.11  85475.11  85475.11  85475.11  0.00000
9  2026-10-07 00:50:00+00:00  85475.11  85475.11  85475.11  85475.11  0.00000
10 2026-10-07 00:55:00+00:00  85475.11  85475.11  85475.11  85475.11  0.00000
11 2026-10-07 01:00:00+00:00  85475.11  85475.11  85475.11  85475.11  0.07143
12 2026-10-07 01:05:00+00:00  85480.52  85480.52  85480.52  85480.52  0.00026
13 2026-10-07 01:10:00+00:00  85480.52  85480.52  85480.52  85480.52  0.00000
14 2026-10-07 01:15:00+00:00  85400.00  85400.00  85392.06  85392.06  0.35345
15 2026-10-07 01:20:00+00:00  85350.00  85350.00  85300.00  85300.00  0.08094
16 2026-10-07 01:25:00+00:00  85309.02  85309.02  85255.65  85255.65  0.13403
17 2026-10-07 01:30:00+00:00  85309.03  85316.88  85309.02  85316.88  0.09854
18 2026-10-07 01:35:00+00:00  85225.97  85309.03  85195.54  85277.25  0.22911
19 2026-10-07 01:40:00+00:00  85272.08  85272.08  85272.08  85272.08  0.00015
20 2026-10-07 01:45:00+00:00  85309.03  85309.03  85309.03  85309.03  0.00397
21 2026-10-07 01:50:00+00:00  85225.97  85225.97  85015.87  85015.87  0.13150
22 2026-10-07 01:55:00+00:00  85059.88  85059.88  84395.51  84395.51  0.60155
23 2026-10-07 02:00:00+00:00  84365.82  84501.38  83590.91  83814.18  1.52914
24 2026-10-07 02:05:00+00:00  83731.13  83980.27  83524.85  83851.85  1.01917
25 2026-10-07 02:10:00+00:00  83961.86  84063.33  83920.70  83920.70  0.39280
26 2026-10-07 02:15:00+00:00  83897.23  84063.33  83897.23  84063.33  0.36340
27 2026-10-07 02:20:00+00:00  83980.27  83980.27  83767.26  83814.18  0.33560
28 2026-10-07 02:25:00+00:00  83814.18  83858.04  83731.13  83814.19  0.26307
29 2026-10-07 02:30:00+00:00  83814.19  83814.19  83814.18  83814.18  0.19286
30 2026-10-07 02:35:00+00:00  83897.24  83980.27  83897.23  83897.23  0.41894
31 2026-10-07 02:40:00+00:00  83814.18  83814.18  83814.18  83814.18  0.08332
32 2026-10-07 02:45:00+00:00  83814.18  83814.18  83814.18  83814.18  0.03902
33 2026-10-07 02:50:00+00:00  83814.18  83814.18  83814.18  83814.18  0.04319
34 2026-10-07 02:55:00+00:00  83858.95  83858.95  83856.60  83856.60  0.00023
35 2026-10-07 03:00:00+00:00  83897.24  83980.28  83897.24  83980.28  0.31257
36 2026-10-07 03:05:00+00:00  83980.27  84063.33  83980.27  84063.33  0.38154
37 2026-10-07 03:10:00+00:00  84063.32  84063.32  83980.27  83980.27  0.12155
38 2026-10-07 03:15:00+00:00  84063.33  84131.79  84063.33  84131.79  0.05633
39 2026-10-07 03:20:00+00:00  84063.32  84063.32  83980.27  83980.28  0.22835
40 2026-10-07 03:25:00+00:00  83980.27  83980.27  83951.83  83951.83  0.05128
41 2026-10-07 03:30:00+00:00  83951.83  83951.83  83951.83  83951.83  0.00000
42 2026-10-07 03:35:00+00:00  84063.33  84120.00  84063.33  84120.00  0.20118
43 2026-10-07 03:40:00+00:00  84120.00  84120.00  84120.00  84120.00  0.00000
44 2026-10-07 03:45:00+00:00  84146.38  84146.38  84146.38  84146.38  0.17183

    log_return_5m  log_return_15m        rsi        macd  bollinger_hband  \
0             NaN             NaN        NaN         NaN              NaN
1    9.725600e-04             NaN        NaN         NaN              NaN
2   -1.168796e-07             NaN        NaN         NaN              NaN
3   -9.711562e-04    1.286925e-06        NaN         NaN              NaN
4    0.000000e+00   -9.712730e-04        NaN         NaN              NaN
5   -8.791217e-04   -1.850278e-03        NaN         NaN              NaN
6    0.000000e+00   -8.791217e-04        NaN         NaN              NaN
7    8.791217e-04    0.000000e+00        NaN         NaN              NaN
8    0.000000e+00    8.791217e-04        NaN         NaN              NaN
9    0.000000e+00    8.791217e-04        NaN         NaN              NaN
10   0.000000e+00    0.000000e+00        NaN         NaN              NaN
11   0.000000e+00    0.000000e+00        NaN         NaN              NaN
12   6.329128e-05    6.329128e-05        NaN         NaN              NaN
13   0.000000e+00    6.329128e-05  51.854726         NaN              NaN
14  -1.035391e-03   -9.721002e-04  33.122910         NaN              NaN
15  -1.078668e-03   -2.114059e-03  23.577447         NaN              NaN
16  -5.200649e-04   -2.634124e-03  20.510833         NaN              NaN
17   7.179351e-04   -8.807975e-04  33.391723         NaN              NaN
18  -4.646115e-04   -2.667413e-04  30.002923         NaN              NaN
19  -6.062762e-05    1.926959e-04  29.581155         NaN     85606.398873
20   4.332250e-04   -9.201416e-05  36.456430         NaN     85603.220875
21  -3.442366e-03   -3.069768e-03  19.875806         NaN     85634.222624
22  -7.323744e-03   -1.033288e-02   9.760002         NaN     85819.209912
23  -6.911996e-03   -1.767810e-02   6.448132         NaN     86064.551555
24   4.493457e-04   -1.378639e-02   8.612192         NaN     86176.762128
25   8.207541e-04   -5.641896e-03  12.591989 -353.302808     86232.070356
26   1.698138e-03    2.968238e-03  20.332108 -374.065860     86239.726693
27  -2.968238e-03   -4.493457e-04  17.428768 -405.945563     86246.390699
28   1.193115e-07   -1.269980e-03  17.429278 -426.295581     86227.234854
29  -1.193115e-07   -2.968238e-03  17.429162 -437.382055     86185.778392
30   9.903918e-04    9.903918e-04  22.062451 -434.458557     86118.327172
31  -9.903918e-04   -1.193115e-07  20.805207 -433.842044     86038.048956
32   0.000000e+00    0.000000e+00  20.805207 -428.414952     85937.285980
33   0.000000e+00   -9.903918e-04  20.805207 -419.280735     85816.152023
34   5.059916e-04    5.059916e-04  23.583252 -403.962238     85690.369787
35   1.473812e-03    1.979804e-03  31.164939 -377.490797     85562.579766
36   9.884340e-04    2.968238e-03  35.773015 -345.824104     85427.929063
37  -9.885531e-04    1.473693e-03  33.367177 -323.698870     85257.985410
38   1.802608e-03    1.802489e-03  41.143401 -290.588343     85075.839661
39  -1.802489e-03   -9.884340e-04  36.550098 -273.421767     84852.755318
40  -3.388274e-04   -3.387083e-04  35.743154 -259.125769     84540.063895
41   0.000000e+00   -2.141316e-03  35.743154 -244.972200     84221.614098
42   2.001169e-03    1.662341e-03  44.190134 -217.676245     84135.180996
43   0.000000e+00    2.001169e-03  44.190134 -193.809884     84160.859851
44   3.135505e-04    2.314719e-03  45.493675 -170.798121     84189.421049

    bollinger_lband  bollinger_mavg
0               NaN             NaN
1               NaN             NaN
2               NaN             NaN
3               NaN             NaN
4               NaN             NaN
5               NaN             NaN
6               NaN             NaN
7               NaN             NaN
8               NaN             NaN
9               NaN             NaN
10              NaN             NaN
11              NaN             NaN
12              NaN             NaN
13              NaN             NaN
14              NaN             NaN
15              NaN             NaN
16              NaN             NaN
17              NaN             NaN
18              NaN             NaN
19     85242.807127      85424.6030
20     85229.388125      85416.3045
21     85144.156376      85389.1895
22     84842.904088      85331.0570
23     84431.469445      85248.0105
24     84156.932872      85166.8475
25     83953.694644      85092.8825
26     83812.371307      85026.0490
27     83639.614301      84943.0025
28     83492.678146      84859.9565
29     83368.041608      84776.9100
30     83277.704828      84698.0160
31     83191.890044      84614.9695
32     83126.019020      84531.6525
33     83080.518977      84448.3355
34     83052.755213      84371.5625
35     83048.573234      84305.5765
36     83063.991937      84245.9605
37     83100.274590      84179.1300
38     83167.874339      84121.8570
39     83261.778682      84057.2670
40     83438.750105      83989.4070
41     83650.795902      83936.2050
42     83709.678004      83922.4295
43     83714.581149      83937.7205
44     83715.472951      83952.4470

In [15]:
#Adding the target variable to the dataset
df4["target_log_return_5m"] = np.log(
    df4["close"].shift(-1) / df4["close"]
)
df4["target_log_return_15m"] = np.log(
    df4["close"].shift(-3) / df4["close"]
)
print("First 45 rows of the dataset with new features:")
print(df4.head(45))

First 45 rows of the dataset with new features:
                    Datetime      open      high       low     close   volume  \
0  2026-10-07 00:05:00+00:00  85475.12  85475.12  85475.00  85475.00  0.09046
1  2026-10-07 00:10:00+00:00  85557.34  85558.17  85557.34  85558.17  0.07562
2  2026-10-07 00:15:00+00:00  85558.16  85558.16  85558.16  85558.16  0.07507
3  2026-10-07 00:20:00+00:00  85475.11  85475.11  85475.11  85475.11  0.15344
4  2026-10-07 00:25:00+00:00  85475.11  85475.11  85475.11  85475.11  0.00000
5  2026-10-07 00:30:00+00:00  85400.00  85400.00  85400.00  85400.00  0.00450
6  2026-10-07 00:35:00+00:00  85400.00  85400.00  85400.00  85400.00  0.00000
7  2026-10-07 00:40:00+00:00  85475.11  85475.11  85475.11  85475.11  0.14730
8  2026-10-07 00:45:00+00:00  85475.11  85475.11  85475.11  85475.11  0.00000
9  2026-10-07 00:50:00+00:00  85475.11  85475.11  85475.11  85475.11  0.00000
10 2026-10-07 00:55:00+00:00  85475.11  85475.11  85475.11  85475.11  0.00000
11 2026-10-07 01:00:00+00:00  85475.11  85475.11  85475.11  85475.11  0.07143
12 2026-10-07 01:05:00+00:00  85480.52  85480.52  85480.52  85480.52  0.00026
13 2026-10-07 01:10:00+00:00  85480.52  85480.52  85480.52  85480.52  0.00000
14 2026-10-07 01:15:00+00:00  85400.00  85400.00  85392.06  85392.06  0.35345
15 2026-10-07 01:20:00+00:00  85350.00  85350.00  85300.00  85300.00  0.08094
16 2026-10-07 01:25:00+00:00  85309.02  85309.02  85255.65  85255.65  0.13403
17 2026-10-07 01:30:00+00:00  85309.03  85316.88  85309.02  85316.88  0.09854
18 2026-10-07 01:35:00+00:00  85225.97  85309.03  85195.54  85277.25  0.22911
19 2026-10-07 01:40:00+00:00  85272.08  85272.08  85272.08  85272.08  0.00015
20 2026-10-07 01:45:00+00:00  85309.03  85309.03  85309.03  85309.03  0.00397
21 2026-10-07 01:50:00+00:00  85225.97  85225.97  85015.87  85015.87  0.13150
22 2026-10-07 01:55:00+00:00  85059.88  85059.88  84395.51  84395.51  0.60155
23 2026-10-07 02:00:00+00:00  84365.82  84501.38  83590.91  83814.18  1.52914
24 2026-10-07 02:05:00+00:00  83731.13  83980.27  83524.85  83851.85  1.01917
25 2026-10-07 02:10:00+00:00  83961.86  84063.33  83920.70  83920.70  0.39280
26 2026-10-07 02:15:00+00:00  83897.23  84063.33  83897.23  84063.33  0.36340
27 2026-10-07 02:20:00+00:00  83980.27  83980.27  83767.26  83814.18  0.33560
28 2026-10-07 02:25:00+00:00  83814.18  83858.04  83731.13  83814.19  0.26307
29 2026-10-07 02:30:00+00:00  83814.19  83814.19  83814.18  83814.18  0.19286
30 2026-10-07 02:35:00+00:00  83897.24  83980.27  83897.23  83897.23  0.41894
31 2026-10-07 02:40:00+00:00  83814.18  83814.18  83814.18  83814.18  0.08332
32 2026-10-07 02:45:00+00:00  83814.18  83814.18  83814.18  83814.18  0.03902
33 2026-10-07 02:50:00+00:00  83814.18  83814.18  83814.18  83814.18  0.04319
34 2026-10-07 02:55:00+00:00  83858.95  83858.95  83856.60  83856.60  0.00023
35 2026-10-07 03:00:00+00:00  83897.24  83980.28  83897.24  83980.28  0.31257
36 2026-10-07 03:05:00+00:00  83980.27  84063.33  83980.27  84063.33  0.38154
37 2026-10-07 03:10:00+00:00  84063.32  84063.32  83980.27  83980.27  0.12155
38 2026-10-07 03:15:00+00:00  84063.33  84131.79  84063.33  84131.79  0.05633
39 2026-10-07 03:20:00+00:00  84063.32  84063.32  83980.27  83980.28  0.22835
40 2026-10-07 03:25:00+00:00  83980.27  83980.27  83951.83  83951.83  0.05128
41 2026-10-07 03:30:00+00:00  83951.83  83951.83  83951.83  83951.83  0.00000
42 2026-10-07 03:35:00+00:00  84063.33  84120.00  84063.33  84120.00  0.20118
43 2026-10-07 03:40:00+00:00  84120.00  84120.00  84120.00  84120.00  0.00000
44 2026-10-07 03:45:00+00:00  84146.38  84146.38  84146.38  84146.38  0.17183

    log_return_5m  log_return_15m        rsi        macd  bollinger_hband  \
0             NaN             NaN        NaN         NaN              NaN
1    9.725600e-04             NaN        NaN         NaN              NaN
2   -1.168796e-07             NaN        NaN         NaN              NaN
3   -9.711562e-04    1.286925e-06        NaN         NaN              NaN
4    0.000000e+00   -9.712730e-04        NaN         NaN              NaN
5   -8.791217e-04   -1.850278e-03        NaN         NaN              NaN
6    0.000000e+00   -8.791217e-04        NaN         NaN              NaN
7    8.791217e-04    0.000000e+00        NaN         NaN              NaN
8    0.000000e+00    8.791217e-04        NaN         NaN              NaN
9    0.000000e+00    8.791217e-04        NaN         NaN              NaN
10   0.000000e+00    0.000000e+00        NaN         NaN              NaN
11   0.000000e+00    0.000000e+00        NaN         NaN              NaN
12   6.329128e-05    6.329128e-05        NaN         NaN              NaN
13   0.000000e+00    6.329128e-05  51.854726         NaN              NaN
14  -1.035391e-03   -9.721002e-04  33.122910         NaN              NaN
15  -1.078668e-03   -2.114059e-03  23.577447         NaN              NaN
16  -5.200649e-04   -2.634124e-03  20.510833         NaN              NaN
17   7.179351e-04   -8.807975e-04  33.391723         NaN              NaN
18  -4.646115e-04   -2.667413e-04  30.002923         NaN              NaN
19  -6.062762e-05    1.926959e-04  29.581155         NaN     85606.398873
20   4.332250e-04   -9.201416e-05  36.456430         NaN     85603.220875
21  -3.442366e-03   -3.069768e-03  19.875806         NaN     85634.222624
22  -7.323744e-03   -1.033288e-02   9.760002         NaN     85819.209912
23  -6.911996e-03   -1.767810e-02   6.448132         NaN     86064.551555
24   4.493457e-04   -1.378639e-02   8.612192         NaN     86176.762128
25   8.207541e-04   -5.641896e-03  12.591989 -353.302808     86232.070356
26   1.698138e-03    2.968238e-03  20.332108 -374.065860     86239.726693
27  -2.968238e-03   -4.493457e-04  17.428768 -405.945563     86246.390699
28   1.193115e-07   -1.269980e-03  17.429278 -426.295581     86227.234854
29  -1.193115e-07   -2.968238e-03  17.429162 -437.382055     86185.778392
30   9.903918e-04    9.903918e-04  22.062451 -434.458557     86118.327172
31  -9.903918e-04   -1.193115e-07  20.805207 -433.842044     86038.048956
32   0.000000e+00    0.000000e+00  20.805207 -428.414952     85937.285980
33   0.000000e+00   -9.903918e-04  20.805207 -419.280735     85816.152023
34   5.059916e-04    5.059916e-04  23.583252 -403.962238     85690.369787
35   1.473812e-03    1.979804e-03  31.164939 -377.490797     85562.579766
36   9.884340e-04    2.968238e-03  35.773015 -345.824104     85427.929063
37  -9.885531e-04    1.473693e-03  33.367177 -323.698870     85257.985410
38   1.802608e-03    1.802489e-03  41.143401 -290.588343     85075.839661
39  -1.802489e-03   -9.884340e-04  36.550098 -273.421767     84852.755318
40  -3.388274e-04   -3.387083e-04  35.743154 -259.125769     84540.063895
41   0.000000e+00   -2.141316e-03  35.743154 -244.972200     84221.614098
42   2.001169e-03    1.662341e-03  44.190134 -217.676245     84135.180996
43   0.000000e+00    2.001169e-03  44.190134 -193.809884     84160.859851
44   3.135505e-04    2.314719e-03  45.493675 -170.798121     84189.421049

    bollinger_lband  bollinger_mavg  target_log_return_5m  \
0               NaN             NaN          9.725600e-04
1               NaN             NaN         -1.168796e-07
2               NaN             NaN         -9.711562e-04
3               NaN             NaN          0.000000e+00
4               NaN             NaN         -8.791217e-04
5               NaN             NaN          0.000000e+00
6               NaN             NaN          8.791217e-04
7               NaN             NaN          0.000000e+00
8               NaN             NaN          0.000000e+00
9               NaN             NaN          0.000000e+00
10              NaN             NaN          0.000000e+00
11              NaN             NaN          6.329128e-05
12              NaN             NaN          0.000000e+00
13              NaN             NaN         -1.035391e-03
14              NaN             NaN         -1.078668e-03
15              NaN             NaN         -5.200649e-04
16              NaN             NaN          7.179351e-04
17              NaN             NaN         -4.646115e-04
18              NaN             NaN         -6.062762e-05
19     85242.807127      85424.6030          4.332250e-04
20     85229.388125      85416.3045         -3.442366e-03
21     85144.156376      85389.1895         -7.323744e-03
22     84842.904088      85331.0570         -6.911996e-03
23     84431.469445      85248.0105          4.493457e-04
24     84156.932872      85166.8475          8.207541e-04
25     83953.694644      85092.8825          1.698138e-03
26     83812.371307      85026.0490         -2.968238e-03
27     83639.614301      84943.0025          1.193115e-07
28     83492.678146      84859.9565         -1.193115e-07
29     83368.041608      84776.9100          9.903918e-04
30     83277.704828      84698.0160         -9.903918e-04
31     83191.890044      84614.9695          0.000000e+00
32     83126.019020      84531.6525          0.000000e+00
33     83080.518977      84448.3355          5.059916e-04
34     83052.755213      84371.5625          1.473812e-03
35     83048.573234      84305.5765          9.884340e-04
36     83063.991937      84245.9605         -9.885531e-04
37     83100.274590      84179.1300          1.802608e-03
38     83167.874339      84121.8570         -1.802489e-03
39     83261.778682      84057.2670         -3.388274e-04
40     83438.750105      83989.4070          0.000000e+00
41     83650.795902      83936.2050          2.001169e-03
42     83709.678004      83922.4295          0.000000e+00
43     83714.581149      83937.7205          3.135505e-04
44     83715.472951      83952.4470          5.420036e-04

    target_log_return_15m
0            1.286925e-06
1           -9.712730e-04
2           -1.850278e-03
3           -8.791217e-04
4            0.000000e+00
5            8.791217e-04
6            8.791217e-04
7            0.000000e+00
8            0.000000e+00
9            6.329128e-05
10           6.329128e-05
11          -9.721002e-04
12          -2.114059e-03
13          -2.634124e-03
14          -8.807975e-04
15          -2.667413e-04
16           1.926959e-04
17          -9.201416e-05
18          -3.069768e-03
19          -1.033288e-02
20          -1.767810e-02
21          -1.378639e-02
22          -5.641896e-03
23           2.968238e-03
24          -4.493457e-04
25          -1.269980e-03
26          -2.968238e-03
27           9.903918e-04
28          -1.193115e-07
29           0.000000e+00
30          -9.903918e-04
31           5.059916e-04
32           1.979804e-03
33           2.968238e-03
34           1.473693e-03
35           1.802489e-03
36          -9.884340e-04
37          -3.387083e-04
38          -2.141316e-03
39           1.662341e-03
40           2.001169e-03
41           2.314719e-03
42           8.555540e-04
43           3.134316e-04
44          -1.188405e-07

In [17]:
#Dropping the missing values from the dataset
df4 = df4.dropna().reset_index(drop=True)
df4 = df4.drop_duplicates().reset_index(drop=True)
print("Dataset after dropping missing values:")
print(df4.isna().sum())
print("Number of duplicate values in the dataset:")
print(df4.duplicated().sum())
print(df4.head(45))

Dataset after dropping missing values:
Datetime                 0
open                     0
high                     0
low                      0
close                    0
volume                   0
log_return_5m            0
log_return_15m           0
rsi                      0
macd                     0
bollinger_hband          0
bollinger_lband          0
bollinger_mavg           0
target_log_return_5m     0
target_log_return_15m    0
dtype: int64
Number of duplicate values in the dataset:
0
                    Datetime      open      high       low     close   volume  \
0  2026-10-07 02:10:00+00:00  83961.86  84063.33  83920.70  83920.70  0.39280
1  2026-10-07 02:15:00+00:00  83897.23  84063.33  83897.23  84063.33  0.36340
2  2026-10-07 02:20:00+00:00  83980.27  83980.27  83767.26  83814.18  0.33560
3  2026-10-07 02:25:00+00:00  83814.18  83858.04  83731.13  83814.19  0.26307
4  2026-10-07 02:30:00+00:00  83814.19  83814.19  83814.18  83814.18  0.19286
5  2026-10-07 02:35:00+00:00  83897.24  83980.27  83897.23  83897.23  0.41894
6  2026-10-07 02:40:00+00:00  83814.18  83814.18  83814.18  83814.18  0.08332
7  2026-10-07 02:45:00+00:00  83814.18  83814.18  83814.18  83814.18  0.03902
8  2026-10-07 02:50:00+00:00  83814.18  83814.18  83814.18  83814.18  0.04319
9  2026-10-07 02:55:00+00:00  83858.95  83858.95  83856.60  83856.60  0.00023
10 2026-10-07 03:00:00+00:00  83897.24  83980.28  83897.24  83980.28  0.31257
11 2026-10-07 03:05:00+00:00  83980.27  84063.33  83980.27  84063.33  0.38154
12 2026-10-07 03:10:00+00:00  84063.32  84063.32  83980.27  83980.27  0.12155
13 2026-10-07 03:15:00+00:00  84063.33  84131.79  84063.33  84131.79  0.05633
14 2026-10-07 03:20:00+00:00  84063.32  84063.32  83980.27  83980.28  0.22835
15 2026-10-07 03:25:00+00:00  83980.27  83980.27  83951.83  83951.83  0.05128
16 2026-10-07 03:30:00+00:00  83951.83  83951.83  83951.83  83951.83  0.00000
17 2026-10-07 03:35:00+00:00  84063.33  84120.00  84063.33  84120.00  0.20118
18 2026-10-07 03:40:00+00:00  84120.00  84120.00  84120.00  84120.00  0.00000
19 2026-10-07 03:45:00+00:00  84146.38  84146.38  84146.38  84146.38  0.17183
20 2026-10-07 03:50:00+00:00  84192.00  84192.00  84192.00  84192.00  0.00023
21 2026-10-07 03:55:00+00:00  84190.00  84190.00  84146.37  84146.37  0.06091
22 2026-10-07 04:00:00+00:00  84146.37  84146.37  84146.37  84146.37  0.00000
23 2026-10-07 04:05:00+00:00  84146.37  84146.37  84063.33  84063.33  0.09674
24 2026-10-07 04:10:00+00:00  84063.33  84063.33  84063.33  84063.33  0.00000
25 2026-10-07 04:15:00+00:00  84063.32  84063.32  84063.32  84063.32  0.11271
26 2026-10-07 04:20:00+00:00  84063.32  84063.32  84063.32  84063.32  0.05322
27 2026-10-07 04:25:00+00:00  84142.12  84146.38  84142.12  84146.38  0.00435
28 2026-10-07 04:30:00+00:00  84063.32  84063.32  84063.32  84063.32  0.05123
29 2026-10-07 04:35:00+00:00  84063.32  84063.32  84063.32  84063.32  0.00000
30 2026-10-07 04:40:00+00:00  84063.32  84063.32  84063.32  84063.32  0.09681
31 2026-10-07 04:45:00+00:00  84063.32  84063.32  84063.32  84063.32  0.00000
32 2026-10-07 04:50:00+00:00  84063.32  84063.32  84063.32  84063.32  0.00000
33 2026-10-07 04:55:00+00:00  84092.58  84092.59  84063.33  84063.33  0.00300
34 2026-10-07 05:00:00+00:00  84063.33  84063.33  84063.33  84063.33  0.00000
35 2026-10-07 05:05:00+00:00  84063.32  84146.38  84063.32  84146.38  0.36918
36 2026-10-07 05:10:00+00:00  84185.96  84188.06  84117.13  84117.13  0.05608
37 2026-10-07 05:15:00+00:00  84146.37  84146.37  84117.13  84117.13  0.05273
38 2026-10-07 05:20:00+00:00  84117.13  84117.13  84117.13  84117.13  0.00000
39 2026-10-07 05:25:00+00:00  84117.13  84117.13  84117.13  84117.13  0.00000
40 2026-10-07 05:30:00+00:00  84117.13  84117.13  84117.13  84117.13  0.00000
41 2026-10-07 05:35:00+00:00  84117.13  84117.13  84117.13  84117.13  0.00000
42 2026-10-07 05:40:00+00:00  84117.13  84117.13  84117.13  84117.13  0.00000
43 2026-10-07 05:45:00+00:00  84229.42  84229.42  84229.42  84229.42  0.01091
44 2026-10-07 05:50:00+00:00  84229.42  84229.42  84229.42  84229.42  0.25762

    log_return_5m  log_return_15m        rsi        macd  bollinger_hband  \
0    8.207541e-04   -5.641896e-03  12.591989 -353.302808     86232.070356
1    1.698138e-03    2.968238e-03  20.332108 -374.065860     86239.726693
2   -2.968238e-03   -4.493457e-04  17.428768 -405.945563     86246.390699
3    1.193115e-07   -1.269980e-03  17.429278 -426.295581     86227.234854
4   -1.193115e-07   -2.968238e-03  17.429162 -437.382055     86185.778392
5    9.903918e-04    9.903918e-04  22.062451 -434.458557     86118.327172
6   -9.903918e-04   -1.193115e-07  20.805207 -433.842044     86038.048956
7    0.000000e+00    0.000000e+00  20.805207 -428.414952     85937.285980
8    0.000000e+00   -9.903918e-04  20.805207 -419.280735     85816.152023
9    5.059916e-04    5.059916e-04  23.583252 -403.962238     85690.369787
10   1.473812e-03    1.979804e-03  31.164939 -377.490797     85562.579766
11   9.884340e-04    2.968238e-03  35.773015 -345.824104     85427.929063
12  -9.885531e-04    1.473693e-03  33.367177 -323.698870     85257.985410
13   1.802608e-03    1.802489e-03  41.143401 -290.588343     85075.839661
14  -1.802489e-03   -9.884340e-04  36.550098 -273.421767     84852.755318
15  -3.388274e-04   -3.387083e-04  35.743154 -259.125769     84540.063895
16   0.000000e+00   -2.141316e-03  35.743154 -244.972200     84221.614098
17   2.001169e-03    1.662341e-03  44.190134 -217.676245     84135.180996
18   0.000000e+00    2.001169e-03  44.190134 -193.809884     84160.859851
19   3.135505e-04    2.314719e-03  45.493675 -170.798121     84189.421049
20   5.420036e-04    8.555540e-04  47.765808 -147.183343     84224.268106
21  -5.421224e-04    3.134316e-04  45.713189 -130.644433     84237.070169
22   0.000000e+00   -1.188405e-07  45.713189 -116.197772     84254.128901
23  -9.873391e-04   -1.529462e-03  41.911870 -110.179245     84256.277907
24   0.000000e+00   -9.873391e-04  41.911870 -104.208271     84255.461715
25  -1.189579e-07   -9.874581e-04  41.911383  -98.343397     84258.870735
26   0.000000e+00   -1.189579e-07  41.911383  -92.627687     84252.326286
27   9.875769e-04    9.874579e-04  47.756139  -80.468112     84249.832878
28  -9.875769e-04    0.000000e+00  43.087296  -76.650233     84230.916141
29   0.000000e+00    0.000000e+00  43.087296  -72.785510     84212.818464
30   0.000000e+00   -9.875769e-04  43.087296  -68.928129     84210.688956
31   0.000000e+00    0.000000e+00  43.087296  -65.120458     84210.688645
32   0.000000e+00    0.000000e+00  43.087296  -61.395127     84207.711028
33   1.189579e-07    1.189579e-07  43.088267  -57.775963     84202.219405
34   0.000000e+00    1.189579e-07  43.088267  -54.282020     84198.584830
35   9.874579e-04    9.875769e-04  51.115792  -44.300931     84195.500678
36  -3.476690e-04    6.397890e-04  48.519991  -38.309468     84182.643243
37   0.000000e+00    6.397890e-04  48.519991  -33.178728     84182.364240
38   0.000000e+00   -3.476690e-04  48.519991  -28.780811     84182.084030
39   0.000000e+00    0.000000e+00  48.519991  -25.007164     84178.211883
40   0.000000e+00    0.000000e+00  48.519991  -21.765621     84162.655158
41   0.000000e+00    0.000000e+00  48.519991  -18.977909     84157.809952
42   0.000000e+00    0.000000e+00  48.519991  -16.577531     84152.644005
43   1.334034e-03    1.334034e-03  61.220621   -5.550369     84184.238068
44   0.000000e+00    1.334034e-03  61.220621    3.152397     84208.028744

    bollinger_lband  bollinger_mavg  target_log_return_5m  \
0      83953.694644      85092.8825          1.698138e-03
1      83812.371307      85026.0490         -2.968238e-03
2      83639.614301      84943.0025          1.193115e-07
3      83492.678146      84859.9565         -1.193115e-07
4      83368.041608      84776.9100          9.903918e-04
5      83277.704828      84698.0160         -9.903918e-04
6      83191.890044      84614.9695          0.000000e+00
7      83126.019020      84531.6525          0.000000e+00
8      83080.518977      84448.3355          5.059916e-04
9      83052.755213      84371.5625          1.473812e-03
10     83048.573234      84305.5765          9.884340e-04
11     83063.991937      84245.9605         -9.885531e-04
12     83100.274590      84179.1300          1.802608e-03
13     83167.874339      84121.8570         -1.802489e-03
14     83261.778682      84057.2670         -3.388274e-04
15     83438.750105      83989.4070          0.000000e+00
16     83650.795902      83936.2050          2.001169e-03
17     83709.678004      83922.4295          0.000000e+00
18     83714.581149      83937.7205          3.135505e-04
19     83715.472951      83952.4470          5.420036e-04
20     83707.755894      83966.0120         -5.421224e-04
21     83703.257831      83970.1640          0.000000e+00
22     83719.418099      83986.7735         -9.873391e-04
23     83742.183093      83999.2305          0.000000e+00
24     83767.914285      84011.6880         -1.189579e-07
25     83781.114265      84019.9925          0.000000e+00
26     83812.572714      84032.4495          9.875769e-04
27     83848.286122      84049.0595         -9.875769e-04
28     83892.116859      84061.5165          0.000000e+00
29     83930.886536      84071.8525          0.000000e+00
30     83941.320044      84076.0045          0.000000e+00
31     83941.319355      84076.0040          0.000000e+00
32     83952.601972      84080.1565          1.189579e-07
33     83951.247595      84076.7335          0.000000e+00
34     83963.187170      84080.8860          9.874579e-04
35     83985.726322      84090.6135         -3.476690e-04
36     84015.113757      84098.8785          0.000000e+00
37     84015.105760      84098.7350          0.000000e+00
38     84015.098970      84098.5915          0.000000e+00
39     84016.046117      84097.1290          0.000000e+00
40     84024.115842      84093.3855          0.000000e+00
41     84026.037048      84091.9235          0.000000e+00
42     84028.278995      84090.4615          1.334034e-03
43     84013.293932      84098.7660          0.000000e+00
44     84006.112256      84107.0705          0.000000e+00

    target_log_return_15m
0           -1.269980e-03
1           -2.968238e-03
2            9.903918e-04
3           -1.193115e-07
4            0.000000e+00
5           -9.903918e-04
6            5.059916e-04
7            1.979804e-03
8            2.968238e-03
9            1.473693e-03
10           1.802489e-03
11          -9.884340e-04
12          -3.387083e-04
13          -2.141316e-03
14           1.662341e-03
15           2.001169e-03
16           2.314719e-03
17           8.555540e-04
18           3.134316e-04
19          -1.188405e-07
20          -1.529462e-03
21          -9.873391e-04
22          -9.874581e-04
23          -1.189579e-07
24           9.874579e-04
25           0.000000e+00
26           0.000000e+00
27          -9.875769e-04
28           0.000000e+00
29           0.000000e+00
30           1.189579e-07
31           1.189579e-07
32           9.875769e-04
33           6.397890e-04
34           6.397890e-04
35          -3.476690e-04
36           0.000000e+00
37           0.000000e+00
38           0.000000e+00
39           0.000000e+00
40           1.334034e-03
41           1.334034e-03
42           1.334034e-03
43           9.853931e-04
44           9.853931e-04

In [18]:
print((df4 == 0).sum())

Datetime                  0
open                      0
high                      0
low                       0
close                     0
volume                   65
log_return_5m            88
log_return_15m           23
rsi                       0
macd                      0
bollinger_hband           0
bollinger_lband           0
bollinger_mavg            0
target_log_return_5m     89
target_log_return_15m    24
dtype: int64

In [19]:
#saving the cleaned dataset to a new CSV file
df4.to_csv('/home/dipankar/Desktop/crypto_price_prediction/data/processed/BTCUSD-5m-2026-10-07_cleaned_data.csv', index=False)